services:
  # Telegram бот
  bot:
    image: ${AURALIS_IMAGE:-auralis-bot:local}
    build: .
    container_name: auralis-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - auralis_network
    restart: unless-stopped

networks:
  auralis_network:
    driver: bridge